### PR TITLE
Use CSV tables

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by marc1706** [comment]
Kinda less readable now?

**Comment by Nicofuma** [comment]
in the file yes. But the output is the same and it's definitely easier to maintain (with the other syntax you can't forget any - or the build will fail)

**Comment by nickvergessen** [comment]
> Kinda less readable now?

You don't read that file like that anyway. And also as explained, when you add/remove one character on the longest column, you had to adjust all the rows, resulting in even more unreadable diffs.

**Comment by michaelcullum** [comment]
:+1:

**Pull request merged**
