### PR TITLE
Update tutorial_authentication.rst

### PR DESCRIPTION
**Pull request by kozfelipe**

### CODE REVIEW

**Comment by paul999** [comment]
Hi,

Thank you for your contribution.
Unfortently, the change you made is incorrect, as the correct path within a extension should be config/. The change you made is only when adding a authentication module hardcoded in core, but this tuturial applies to extensions only.

**Comment by kozfelipe** [comment]
Hi, 

In this case you should explain that in the tutorial and make it clear we have to create *config/auth.ym* which does not exists

**Comment by mrgoldy** [comment]
That paragraph is a bit odd to begin with.
The line that is being changed does indeed refer to the phpBB core authentication providers.
*"Core authentication providers need X and Y. Extension authentication providers need A and B"* 
The core part is no use to it at all in my opinion. 
The service file required by an extension is explained later on: https://area51.phpbb.com/docs/dev/master/extensions/tutorial_authentication.html#the-service-file

**Comment by iMattPro** [comment]
Fixed in #230

**Pull request closed without merging**
