### PR TITLE
Build docs on travis

### PR DESCRIPTION
**Pull request by naderman**

### CODE REVIEW

**Comment by Nicofuma** [comment]
:+1:

**Comment by Nicofuma** [comment]
naderman: you have to configure the branch for continuous-integration/travis-ci/push

**Comment by nickvergessen** [comment]
```yaml
branches:
  only:
    - master
    - /^\d+(\.\d+)?\.x$/

**Comment by naderman** [comment]
What? Why would I have to do that?

**Comment by michaelcullum** [comment]
Can we use circle ci?

**Comment by naderman** [comment]
@michaelcullum can you derail the discussion please

**Comment by naderman** [comment]
@nickvergessen @Nicofuma please explain what you mean?

**Comment by Nicofuma** [comment]
the PR are stored in branch in the phpbb/documentation repo. So the 'continuous-integration/travis-ci/push' job is also triggered for the PRs. @nickvergessen snippet is used in phpbb/phpbb to tell to travis which branch should be built 'on push'

**Comment by naderman** [comment]
I see

**Comment by naderman** [comment]
Pushed

**Comment by nickvergessen** [comment]
> Makefile:12: *** The 'sphinx-build' command was not found. Make sure you have Sphinx installed, then set the SPHINXBUILD environment variable to point to the full path of the 'sphinx-build' executable. Alternatively you can add the directory with the executable to your PATH. If you don't have Sphinx installed, grab it from http://sphinx-doc.org/.  Stop.

you didnt fix that I guess?

**Comment by naderman** [comment]
That was from the old build not the current one? it passed?

**Pull request merged**
