### PR TITLE
Added docs for js linting

### PR DESCRIPTION
**Pull request by callumacrae**
https://github.com/phpbb/phpbb/pull/3668

### CODE REVIEW

**Comment by marc1706** [comment]
Not sure where we would add this, but I guess it would certainly help developers with having proper hinting in PhpStorm: http://rst.ninjs.org/?n=cedca49250c539685ff0dd39bec7fe4e&theme=basic

@nickvergessen ^

**Comment by callumacrae** [comment]
Would probably be best to just send it to people if they complain. It's not related to this PR because it's already an issue.

**Comment by nickvergessen** [comment]
yeah, I'm with callum. Specific stuff should not be here. Feel free to add a doc how to set up phpStorm properly with everything (php libs, js libs, root dir, exclude vendor, ...). But not here.

**Comment by callumacrae** [comment]
Probably worth doing, if they're still giving us a free license

**Comment by marc1706** [comment]
Well definitely not in the coding guidelines. Just pointing out that we might want to add that somewhere in the documentation.

**Comment by nickvergessen** [comment]
@marc1706 https://github.com/phpbb/documentation/issues/new

**Comment by michaelcullum** [comment]
:+1:

**Pull request merged**
